# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{yesradio}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Claudio Baccigalupo"]
  s.date = %q{2009-09-18}
  s.description = %q{YesRadio makes available as a ruby gem the method exposed by Yes.com API to retrieve songs broadcast by thousands of radios.}
  s.email = %q{claudiob@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "features/step_definitions/yesradio_steps.rb",
     "features/support/env.rb",
     "features/yesradio.feature",
     "lib/item.rb",
     "lib/main.rb",
     "lib/song.rb",
     "lib/station.rb",
     "lib/yesradio.rb",
     "test/test_helper.rb",
     "test/yesradio_test.rb",
     "yesradio.gemspec"
  ]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/claudiob/yesradio}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{yesradio}
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{Ruby library for Yes.com radio Web Services (http://api.yes.com).}
  s.test_files = [
    "test/test_helper.rb",
     "test/yesradio_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.3.2"])
    else
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 1.3.2"])
    end
  else
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 1.3.2"])
  end
end
